### PR TITLE
updated gen.utils to convert _id from string to ObjectId for mongoose

### PR DESCRIPTION
**Pull request by skarif2**

### CODE REVIEW

**Comment by skarif2** [comment]
Sorry about the duplicate PR. I have closed it(#39). Not really sure about the other two commits and where they came from. Please let me know if any changes needed.

**Comment by e-oj** [comment]
Hey man, thanks for contributing. I've been really tied down these past few weeks.

I see what you're doing there with the model names and I like it, but theres's a getCollection function you could use to solve it more generically. it's [used here](https://github.com/e-oj/Fawn/blob/ddadfe0e18dabca158e270e83ba57126544db956/lib/roller.js#L152) and [defined here](https://github.com/e-oj/Fawn/blob/ddadfe0e18dabca158e270e83ba57126544db956/lib/roller.js#L245). you could move it to gen.utils. 

The condition._id fix does not handle cases where objectIds are used under different field names (someone might have an objectid in obj.someName) but it's a patch that might work for now. The optimal solution would be to recursively encode keys containing special characters instead of converting whole objects to strings. Which is what I'm currently doing with [xcode](https://github.com/e-oj/Fawn/blob/ddadfe0e18dabca158e270e83ba57126544db956/lib/utils/gen.utils.js#L65) This issue also affects dates(#37) and any other objects recognized by MongoDB. I'll accept checking "condition._id" as a temporary fix. I'll be working on escaping special characters over the weekend but if you want to look into it, I won't stop you.

**Comment by skarif2** [comment]
Yap, I tried to use the `getCollection` function but got this error(in my project):
```"Schema hasn't been registered for model \"User\".\nUse mongoose.model(name, schema)"```
Also I forgot to do `step.name.toLowerCase()` in the last PR(#38), so the current process can't find collection too.
And for the `_id`, I am really sorry as I was only thinking about my use-case.

**Comment by kvenkatesh1220** [comment]
Hi, When can I expect the new changes i.e #38. I am facing the issue with Mongoose Id.

**Comment by kvenkatesh1220** [comment]
Other issue I found is "task.run({useMongoose: true})" is not working for Remove and Save Operations.

**Comment by kvenkatesh1220** [comment]
Is there any option to create Doc if not exists.

**Comment by skarif2** [comment]
Hey @kvenkatesh1220, could you please explain a bit about you question, _Is there any option to create Doc if not exists?_ 
I am free this weekend, so let me see if I can put some time and come up with a new PR. By then, if you have time please read issue #34 and try to understand why [Fawn](https://github.com/e-oj/Fawn/) is causing this error. You are always welcome to make a PR(on behalf of @e-oj).

**Comment by kvenkatesh1220** [comment]
Hi,

So My requirement is like below.

I am getting an array of Objects with data. I need to update the collection
documents if the document is present. If Document is not present then need
to create the document with data.

The array is dynamic, I don't know the length of an array.

and One more thing

I am getting "OverwriteModelError", Could you please help me in this. I
defined my schema as below.

var studentSummary_schema = new mongoose.Schema({
"studentId"     : { type : String, required : true }, //{ type:
mongoose.Schema.Types.ObjectId, ref: "Student", required : true},
"fullName"      : { type : String },
"gender"        : { type : String },
});

studentSummary_schema.plugin(QueryPlugin);

var collectionName = 'studentSummary';
var StudentSummary = mongoose.model('StudentSummary', studentSummary_schema,
collectionName);


var Promise = require('bluebird');
Promise.promisifyAll(StudentSummary);
Promise.promisifyAll(StudentSummary.prototype);

module.exports = StudentSummary;

How can I do findOne() and How can I Use InitModel Option.

Regards,
Venkatesh Konduru.

**Comment by kvenkatesh1220** [comment]
HI,

The code is not updating the MongoDB Doc.

I enabled mongoose DEBUG. Please find the debug query.


My Logic:

var statsDocOfNewCollegeObj = statsDocOfNewCollege.toObject();
                    delete statsDocOfNewCollegeObj._id;
                    delete statsDocOfNewCollegeObj.__v;
                    delete statsDocOfNewCollegeObj.institutionId;
                    task.update('collegesSummary', {"_id" :
statsDocOfNewCollege._id, "institutionId" : statsDocOfNewCollege.
institutionId}, statsDocOfNewCollegeObj);


Debug Query:


Mongoose: ojlinttaskcollections.updateOne({
_id: ObjectId("5a45da633025292394599dd2")
}, {
__v: 0,
_id: ObjectId("5a45da633025292394599dd2"),
steps: [{
index: 0,
type: 'update',
state: 2,
name: 'collegesSummary',
condition:
'{"_id":"5a45da1c3025292394599dd0","institutionId":"59b781fc8b43cf255c021d88"}',
data:
'{"classifiers":{"majors":[],"subjects":[],"years":[],"degrees":[]},"students":{"gradeBucket":{"86-100":1,"76-85":0,"66-75":0,"51-65":0,"00-50":0},"internshipPref":{"0":1,"1":0},"jobPref":{"0":0,"1":1},"gender":{"female":0,"male":1},"dataValid":0,"notValidated":0,"yetToRespond":0,"validated":1,"withTests":0,"withProjects":0,"withPatents":0,"withPapers":0,"withInternships":0,"withHonors":0,"withDiplomas":0,"count":1},"classArray":[{"degree":"Bachelor","subject":"Accounting","major":"Accountancy","_id":"5a45da1c3025292394599dd1","gradeBucket":{"86-100":1,"76-85":0,"66-75":0,"51-65":0,"00-50":0},"internshipPref":{"0":1,"1":0},"jobPref":{"0":0,"1":1},"gender":{"female":0,"male":1},"dataValid":0,"notValidated":0,"validated":1,"withTests":0,"withProjects":0,"withPatents":0,"withPapers":0,"withInternships":0,"withHonors":0,"withDiplomas":0,"count":1,"year":2023}]}',
options: {
multi: true
},
_id: ObjectId("5a45da633025292394599dd5"),
dataStore: []
}
]
})
collection.js: 184
Mongoose: ojlinttaskcollections.updateOne({
_id: ObjectId("5a45da633025292394599dd2")
}, {
__v: 0,
_id: ObjectId("5a45da633025292394599dd2"),
steps: [{
index: 0,
type: 'update',
state: 2,
name: 'collegesSummary',
condition:
'{"_id":"5a45da1c3025292394599dd0","institutionId":"59b781fc8b43cf255c021d88"}',
data:
'{"classifiers":{"majors":[],"subjects":[],"years":[],"degrees":[]},"students":{"gradeBucket":{"86-100":1,"76-85":0,"66-75":0,"51-65":0,"00-50":0},"internshipPref":{"0":1,"1":0},"jobPref":{"0":0,"1":1},"gender":{"female":0,"male":1},"dataValid":0,"notValidated":0,"yetToRespond":0,"validated":1,"withTests":0,"withProjects":0,"withPatents":0,"withPapers":0,"withInternships":0,"withHonors":0,"withDiplomas":0,"count":1},"classArray":[{"degree":"Bachelor","subject":"Accounting","major":"Accountancy","_id":"5a45da1c3025292394599dd1","gradeBucket":{"86-100":1,"76-85":0,"66-75":0,"51-65":0,"00-50":0},"internshipPref":{"0":1,"1":0},"jobPref":{"0":0,"1":1},"gender":{"female":0,"male":1},"dataValid":0,"notValidated":0,"validated":1,"withTests":0,"withProjects":0,"withPatents":0,"withPapers":0,"withInternships":0,"withHonors":0,"withDiplomas":0,"count":1,"year":2023}]}',
options: {
multi: true
},
_id: ObjectId("5a45da633025292394599dd5"),
dataStore: []
}
]
})
collection.js: 184
Mongoose: ojlinttaskcollections.deleteOne({
_id: ObjectId("5a45da633025292394599dd2")
})

**Comment by e-oj** [comment]
The issue related to this pr has been fixed. Thanks for contributing though, much appreciated.

**Comment by e-oj** [comment]
@kvenkatesh1220 you don't have to use initModel if you've already defined the model with Mongoose [as stated in the docs](https://github.com/e-oj/Fawn#task_initmodel). #34 has been fixed and closed. Also, #25 is about upserts but you can open a new issue if it does not cover your case. Fawn tasks don't take effect till task.run is called, so a workaround would be to build the task with a loop and if statements e.g:

```javascript
(async () => {
  let items = req.body.items
  let Item = mongoose.model("Items", ItemSchema);
  let task = Fawn.Task();

  for (let item of items){
    let exists = !! (await Item.findOne(item));

    if(exists){
      task.update(.....);
    }
    else{
      task.save(...); 
    }
  }

  let results = await task.run();
})();
```

**Pull request closed without merging**
